!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers:
  0: Pixy Cam
mDefaultSpiWrappers:
  0: ADXRS450
  1: Dotstar
mDigitalIO: []
mEncoders: []
mGyros:
- mHandle: 100
  mName: ADXRS450 Gyro
  mType: com.snobot.simulator.simulator_components.adx_family.ADXRS450GyroWrapper
mPwm:
- mHandle: 0
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 12.0
  mName: Drive Right
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 12.0
  mName: Drive Left
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
mRelays: []
mSimulatorComponents:
- !!com.snobot.simulator.simulator_components.config.TankDriveConfig
  mGyroHandle: 100
  mLeftMotorHandle: 0
  mRightMotorHandle: 1
  mTurnKp: 1.0
mSolenoids: []
